spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 # localhost 改为 nacos
    gateway:
      routes:
        - id: noj-backend-user-service
          uri: lb://noj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: noj-backend-question-service
          uri: lb://noj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: noj-backend-judge-service
          uri: lb://noj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: noj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: swagger2